### PR TITLE
Use systemd timer in lieu of cron + New Checkbox Support + Typo + New Script Support

### PR DESCRIPTION
**Pull request by ipitio**
This is part of https://github.com/arevindh/AdminLTE/pull/70

Features:
* Schedule
  * Used systemd timer+service to schedule tests
    * Benefits available [here](https://unix.stackexchange.com/a/281203)
    * Some more discussion: https://github.com/MkLHX/AP_STA_RPI_SAME_WIFI_CHIP/pull/12#issuecomment-1015245698
* Settings
  * Saved chart type selection to setupVars.conf when the form is submitted
  * Run uninstall offline
* Scripts
  * Supported new `mod.sh`

Fixes:
* Typo
  * Chage -> Change

### CODE REVIEW

**Comment by arevindh** [comment]
Don't we need a daemon reload everytime the file is changed ?

**Comment by arevindh** [comment]
@ipitio we might need a way to replace the current crontab with a systemd timer for existing users.

**Comment by ipitio** [comment]
All they would have to do is open Speedtest settings and click save, or that could be automated.

**Comment by ipitio** [comment]
Todo: save current state, check if update/uninstall failed, and if so, restore saved state and notify user that command(s) failed and to try again or attempt manually

**Comment by arevindh** [comment]
@ipitio how about we add code to remove existing crontab if they save settings and remove it after a few future releases?

**Comment by ipitio** [comment]
> @ipitio how about we add code to remove existing crontab if they save settings and remove it after a few future releases?

That's exactly what it does at the moment!

**Comment by ipitio** [comment]
> Todo: use screen, copy modded admin and pihole, check if update/uninstall failed, and if so, move them back and notify user that command(s) failed and to try again or attempt manually

Done

**Comment by ipitio** [comment]
The tmux session is killed after it completes, but all the output is saved to a file. Should an operation fail, mod.sh should restore the mod to its prior state.

**Pull request merged**
